version: '3.8'

services:
  # Google Ads Funnel backend service
  google-ads-backend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./code:/app
      - /app/node_modules
    command: >
      sh -c "
        npm install &&
        npm start
      "
    environment:
      - NODE_ENV=development
      - PORT=3000
      - GOOGLE_ADS_CLIENT_ID=${GOOGLE_ADS_CLIENT_ID}
      - GOOGLE_ADS_CLIENT_SECRET=${GOOGLE_ADS_CLIENT_SECRET}
      - GOOGLE_ADS_DEVELOPER_TOKEN=${GOOGLE_ADS_DEVELOPER_TOKEN}
      - GOOGLE_ADS_MANAGER_ID=${GOOGLE_ADS_MANAGER_ID}

  # Frontend for landing pages (example)
  landing-page-example:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./code/public:/usr/share/nginx/html

volumes:
  # No persistent volumes needed for this example
