version: '3.8'
services:
  backend:
    build: ./code
    ports:
      - "3011:3011"
    volumes:
      - ./code:/app
    environment:
      NODE_ENV: development
  frontend:
    build: ./templates
    ports:
      - "91:91"
    volumes:
      - ./templates:/usr/share/nginx/html
    depends_on:
      - backend
