version: '3.8'

services:
  # Static site server for story examples
  story-site:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./code:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  # Development server with hot reload
  dev-server:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - ./code:/app
      - /app/node_modules
    command: >
      sh -c "
        npm install -g live-server &&
        live-server --port=3001 --host=0.0.0.0 --no-browser --watch=/app
      "
    environment:
      - NODE_ENV=development

  # Story analytics service
  analytics:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3002:3002"
    volumes:
      - ./code/analytics:/app
    command: >
      sh -c "
        npm install express cors &&
        node server.js
      "
    environment:
      - PORT=3002
      - NODE_ENV=development

  # A/B testing service
  ab-testing:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3003:3003"
    volumes:
      - ./code/ab-testing:/app
    command: >
      sh -c "
        npm install express cors &&
        node ab-server.js
      "
    environment:
      - PORT=3003
      - NODE_ENV=development