version: '3.8'
services:
  backend:
    build: ./code
    ports:
      - "3014:3014"
    volumes:
      - ./code:/app
    environment:
      NODE_ENV: development
  frontend:
    build: ./templates
    ports:
      - "94:94"
    volumes:
      - ./templates:/usr/share/nginx/html
    depends_on:
      - backend
